name: skeleton
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  google_fonts: ^6.1.0
  fluttertoast: ^8.2.4
  intl: ^0.18.1
  dots_indicator: ^3.0.0
  form_builder_validators: ^9.1.0
  flutter_form_builder: ^9.2.0
  carousel_slider: ^4.2.1
  flutter_custom_clippers: ^2.1.0
  video_player: ^2.8.2
  chewie: ^1.7.4
  dio: ^5.4.0
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  connectivity_plus: ^5.0.2
  cached_network_image: ^3.3.1
  just_audio: ^0.9.36

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/

